### ISSUE TITLE
 LICENSE:md would crash git clone and other git operations

### ISSUE THREAD

**Issue by bacloud22** [christian-fei/minimal-analytics#1]
Thanks for sharing this handy solution. I hope to be able to try it with another web-app I build.

Thanks !

**Comment by christian-fei** [comment]
Please do let me know how it goes!

**Comment by bacloud22** [comment]
Yes @christian-fei  I will work on this these days. 
The concept is great! UI is flat and simple just as I like. 
I'm not sure though if all works well with networking for my case (docker, proxy..) 
Say my web service is in docker and exposed to the internet through a proxy on domain.com, so I need to rebuild with this domain to have client.js ? 
Then include client.js in my delivered scripts on my own domain? Right? 

Also there is an error as a file named "node" is generated for some reason. Also remove ";" in touch command it creates a corrupt file. 
I'm on phone I would pull request if on pc later

**Comment by christian-fei** [comment]
If you need any help, don't hesitate to ping me here :)

**Comment by christian-fei** [comment]
Got it, gonna remove it and update the readme

**Comment by bacloud22** [comment]
hey @christian-fei  ,
Can the server listening port be modified ? I chose to run the stand-alone npm and test it with environment variables.
So in this case I put:
`SITE_BASE_URL=https://ns3027175.ip-188-165-209.eu/ STATS_BASE_URL=0.0.0.0:2020 npm start`

With https://ns3027175.ip-188-165-209.eu/  being my site. Which would be incorporated in "client.js" right ? (because otherwise it is attainable in server if I replace the domain by `0.0.0.0:3000`

But the problem was that minimal_analytics lunched on 127.0.01:8080 but I want to change that too. (8080 taken)

**Comment by christian-fei** [comment]
if you're running it with docker (docker-compose), you can do so by exposing a different port, e.g.:

```
---
version: '3'
services:
  minimal:
    build: .
    ports:
      - "127.0.0.1:YOUR_CUSTOM_PORT:8080"
    restart: always
    environment:
      STATS_BASE_URL: 'https://s.cri.dev'
      SITE_BASE_URL: 'https://cri.dev'
    volumes:
      - ./data:/app/data
      - /app/node_modules
```

hope this answers your question (there is also the option to specify the environment variable `HTTP_PORT`, but there you would need to change also the port exposed in the `Dockerfile` I think, so only useful while developing)

also, please do specify the full url with protocol, also for the `STATS_BASE_URL`
